version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: api_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  www:
    depends_on:
      - db
    build:
      context: .
    container_name: api_server
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html/
    restart: always
    environment:
      DB_HOST: db:3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_EXPIRATION_EPOCH: ${JWT_EXPIRATION_EPOCH}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_SECRET: ${JWT_SECRET}

volumes:
  db_data: {}
