version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  www:
    depends_on:
      - db
    build:
      context: .
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html/
    restart: always
    environment:
      DB_HOST: db:3306
      DB_NAME: database
      DB_USER: admin
      DB_PASSWORD: admin
volumes:
  db_data: {}
